In [2]:
import pandas

#讀取csv檔內容；.csv檔只能是單一頁的資料
df = pandas.read_csv('1120309分析駕訓班學員違規資料__修正版.csv', encoding='big5')  #因為有中文字，需要用big5的編碼方式來解讀
print(type(df))

#印出所有欄位的名稱
#print(df.columns)

#找出特定欄位的資料
vil_name = df.違規人姓名
print(type(vil_name) )

#任取特定欄位資料
want_columns = ['違規人證號','駕駛執照種類']
vil_data = df[want_columns]
#print(vil_data)
#vil_data.describe()  #自行統計出一些數據


#篩選出特定的rows (類似SQL中的where)
is_thirty = df.出生年月日 >= '1993-01-01'  #過濾條件: 小於30歲的
vil_below_30 = df[is_thirty]
#print(vil_below_30)

#多個條件組合
#print(df)
is_big_van = df.駕駛執照種類 == '普通大客車'
is_twenty = df['出生年月日'] >= '2000-01-01'
df_below20_and_big_van = df[is_twenty & is_big_van]
#print(df_below20_and_big_van)

is_coach_and_van = ['普通大貨車','普通大客車']
specified_license = df.駕駛執照種類.isin(is_coach_and_van)
#print(df[specified_license])


#過濾掉null的資料
df_sheets2 = pandas.read_excel('1120309分析駕訓班學員違規資料__修正版.xlsx', sheet_name = '表二result')
#print(df_sheets2)
not_null_data = df_sheets2[df_sheets2.普通大客車.notnull()]
#print(not_null_data)


#for column in df
print('========================================')
df2 = df[[column for column in df ]]
print(df2)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
========================================
    違規人姓名       違規人證號       出生年月日 駕駛執照種類      取得駕照日期             違規日期  \
0     任茂林  H120028888   1975/9/27  普通大客車   2017/5/19  2023/2/20 09:45
1     何建德  H123554143    1987/4/4  普通大客車   2022/7/26   2023/2/1 10:23
2     余松衡  K123075523   1991/8/30  普通大貨車   2015/5/11   2023/1/9 16:08
3     余松衡  K123075523   1991/8/30  普通大貨車   2015/5/11  2023/1/31 00:04
4     余閎榛  H124156954   1991/8/21  普通大客車  2020/12/17  2023/2/14 11:38
..    ...         ...         ...    ...         ...              ...
371   黃浚錡  K121912998  1988/12/11  職業聯結車    2020/6/4  2023/1/30 10:13
372   黃誠緯  H123508285   1980/9/16  普通大貨車    2021/5/5  2023/2/23 13:21
373   黃靖廷  K122269816   1991/6/22  普通大貨車   2016/7/11  2023/2/23 15:10
374   黃鴻晏  K122492708   1991/6/29  普通大貨車    2017/9/1  2023/2/22 07:40
375   黎志康  H123483514  1986/12/26  職業聯結車   2020/7/22   2023/1/8 08:29

         違規條款  違規所駕車輛號牌 違規所駕車輛車種
0    29310012  KLF-7107       汽車
1     3311102   AAH-606       汽車
2    29100021  KLF-8016       汽車
3    29100021  KLF-8016       汽車
4    29310012    147-GB       汽車
..        ...       ...      ...
371   3311103  KLJ-9030       汽車
372  29310012  KLF-7596       汽車
373  29100021  KLL-9118       汽車
374  29100021  KLF-0988       汽車
375  29309012  KLH-0556       汽車

[376 rows x 9 columns]

In [18]:
import pandas

#讀取excel檔內容，可讀取多個worksheets
df = pandas.read_excel('1120309分析駕訓班學員違規資料__修正版.xlsx', sheet_name = ['表一result','表三result'])  #不用特別註明解碼的方式
print(df)

{'表一result':      駕訓班名稱 駕訓班訓練班別        結訓日期 學員名稱        學員證號       出生年月日 駕駛執照種類  \
0    和昭駕訓班  2 大貨車班  2023-02-07  劉浩宇  G121778957  1990-08-22  普通大貨車
1    和昭駕訓班  2 大貨車班  2023-02-07  徐鈺皓  B123430759  2001-03-08  普通大貨車
2    和昭駕訓班  2 大貨車班  2023-02-07  洪子安  H126022568  2002-09-16  普通大貨車
3    和昭駕訓班  2 大貨車班  2023-02-07  蔡君毅  F127494333  1986-12-15  職業大貨車
4    和昭駕訓班  2 大貨車班  2023-02-07  蕭志勇  F123175659  1973-01-23  職業大貨車
..     ...     ...         ...  ...         ...         ...    ...
384  萬駿駕訓班  2 大貨車班  2023-02-23  陳育賢  H125758792  2002-07-09  普通大貨車
385  萬駿駕訓班  2 大貨車班  2023-02-10  魏新帝  H123506718  1986-10-22  普通大貨車
386  萬駿駕訓班  2 大貨車班  2023-02-23  黃安宏  N124438080  1984-06-04  普通大貨車
387  萬駿駕訓班  2 大貨車班  2023-02-10  黃智均  H123010799  1983-04-05  職業大貨車
388  萬駿駕訓班  2 大貨車班  2023-02-10  黃義仁  H124964509  1996-03-26  普通大貨車

         取得駕照日期  違規日期  違規條款  違規所駕車輛號牌  違規所駕車輛車種
0    2023-02-08   NaN   NaN       NaN       NaN
1    2023-02-08   NaN   NaN       NaN       NaN
2    2023-02-08   NaN   NaN       NaN       NaN
3    2023-02-08   NaN   NaN       NaN       NaN
4    2023-02-08   NaN   NaN       NaN       NaN
..          ...   ...   ...       ...       ...
384  2023-02-24   NaN   NaN       NaN       NaN
385  2023-02-17   NaN   NaN       NaN       NaN
386  2023-02-24   NaN   NaN       NaN       NaN
387  2023-02-17   NaN   NaN       NaN       NaN
388  2023-02-17   NaN   NaN       NaN       NaN

[389 rows x 12 columns], '表三result':     違規人姓名       違規人證號       出生年月日 駕駛執照種類      取得駕照日期                 違規日期  \
0     任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2023-02-20 09:45:00
1     何建德  H123554143  1987-04-04  普通大客車  2022-07-26  2023-02-01 10:23:00
2     余松衡  K123075523  1991-08-30  普通大貨車  2015-05-11  2023-01-09 16:08:00
3     余松衡  K123075523  1991-08-30  普通大貨車  2015-05-11  2023-01-31 00:04:00
4     余閎榛  H124156954  1991-08-21  普通大客車  2020-12-17  2023-02-14 11:38:00
..    ...         ...         ...    ...         ...                  ...
371   黃浚錡  K121912998  1988-12-11  職業聯結車  2020-06-04  2023-01-30 10:13:00
372   黃誠緯  H123508285  1980-09-16  普通大貨車  2021-05-05  2023-02-23 13:21:00
373   黃靖廷  K122269816  1991-06-22  普通大貨車  2016-07-11  2023-02-23 15:10:00
374   黃鴻晏  K122492708  1991-06-29  普通大貨車  2017-09-01  2023-02-22 07:40:00
375   黎志康  H123483514  1986-12-26  職業聯結車  2020-07-22  2023-01-08 08:29:00

         違規條款  違規所駕車輛號牌 違規所駕車輛車種
0    29310012  KLF-7107       汽車
1     3311102   AAH-606       汽車
2    29100021  KLF-8016       汽車
3    29100021  KLF-8016       汽車
4    29310012    147-GB       汽車
..        ...       ...      ...
371   3311103  KLJ-9030       汽車
372  29310012  KLF-7596       汽車
373  29100021  KLL-9118       汽車
374  29100021  KLF-0988       汽車
375  29309012  KLH-0556       汽車

[376 rows x 9 columns]}

In [18]:
#處理json檔

import pandas
df = pandas.DataFrame([['a','b'],['c','d']], index = ['row1','row2'], columns = ['col1','col2'])
print(df)

df_json_split = df.to_json(orient = 'split')  #設定轉乘json格式的方式!  split: 個別獨立
df_json_index = df.to_json(orient = 'index')
df_json_records = df.to_json(orient = 'records')
df_json_table = df.to_json(orient = 'table')
df_json_columns = df.to_json(orient = 'columns')
df_json_values = df.to_json(orient = 'values')
print(df_json_split)
print(df_json_index)
print(df_json_records)
print(df_json_table)
print(df_json_columns)
print(df_json_values)


pandas.read_json(df_json_split, orient = 'index')

     col1 col2
row1    a    b
row2    c    d
{"columns":["col1","col2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}
{"row1":{"col1":"a","col2":"b"},"row2":{"col1":"c","col2":"d"}}
[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]
{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}
{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}
[["a","b"],["c","d"]]

              0       1
columns    col1    col2
index      row1    row2
data     [a, b]  [c, d]

In [5]:
#處理xml檔 -> 沒有現成的函數將xml讀入pandas DataFrame中 -> 自己開發
import pandas
import xml.etree.ElementTree as ET
tree = ET.parse('myxml.xml')  #ElementTree is not iterable
print(tree)

root = tree.getroot()  #取得根結點，方便之後的操作
print(root)


#print出每一個element中的內容
for child in root:
    print(child.tag, child.attrib)
    inner_name = child.get('name')  #取得屬性對應的值
    print(inner_name)
    
    #找尋子結點

#用index找出要的node
print(root[0][2].text)


#將xml檔轉換成pandas的DataFrame
columns = ['name','rank','gdppc']
dataframe = pandas.DataFrame(columns = columns)
for country in root:
    name = country.attrib.get('name')
    rank = country.find('rank').text if country is not None else None
    gdppc = country.find('gdppc').text if country is not None else None
    
    #Series的index對應每個column
    #Series是一行資料(column) -> 填入dataframe時，轉置成row, 每個index對應dataframe中的column
    #dataframe的index對應每個row data
    dataframe = dataframe.append(pandas.Series([name,rank,gdppc], index = columns), ignore_index = True)  #Series: 看來是表格中的一行資料(column)
    
print(dataframe)

<xml.etree.ElementTree.ElementTree object at 0x00000215DAB261C0>
<Element 'data' at 0x00000215DAC384A0>
country {'name': 'Liechtenstein'}
Liechtenstein
country {'name': 'Singapore', 'continent': 'Asia'}
Singapore
country {'name': 'Panama'}
Panama
141100
            name rank   gdppc
0  Liechtenstein    1  141100
1      Singapore    4   59900
2         Panama   68   13600

C:\Users\mi83\AppData\Local\Temp\ipykernel_14660\2101666507.py:30: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append(pandas.Series([name,rank,gdppc], index = columns), ignore_index = True)
C:\Users\mi83\AppData\Local\Temp\ipykernel_14660\2101666507.py:30: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append(pandas.Series([name,rank,gdppc], index = columns), ignore_index = True)
C:\Users\mi83\AppData\Local\Temp\ipykernel_14660\2101666507.py:30: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append(pandas.Series([name,rank,gdppc], index = columns), ignore_index = True)

In [7]:
#用dict方式寫入dataframe -> key對應的是column name
import pandas
import numpy as np
df = pandas.DataFrame({'A': pandas.date_range('2013-01-01 09:00:00', periods=3),'B': np.arange(3.0)})  #column : [values]
print(df)

                    A    B
0 2013-01-01 09:00:00  0.0
1 2013-01-02 09:00:00  1.0
2 2013-01-03 09:00:00  2.0

In [40]:
#pandas處理文字
import pandas
ser = pandas.Series(['a','b','c'], index = ['col1','col2','col3'])
print(ser)
print('-----------------------')
print(ser.astype('string'))

df = pandas.DataFrame(columns = ['col1','col3','col22'])
df = df.append(ser, ignore_index=True)
print(df)

col1    a
col2    b
col3    c
dtype: object
-----------------------
col1    a
col2    b
col3    c
dtype: string
  col1 col3 col22 col2
0    a    c   NaN    b

C:\Users\mi83\AppData\Local\Temp\ipykernel_14660\2091120421.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(ser, ignore_index=True)

In [29]:
#pandas的時間
import pandas
import numpy as np
pandas.Series(range(3), index = pandas.date_range('2023-11-03', freq = 'H', periods = 3))

#time delta
friday = pandas.Timestamp('2023-03-17')
saturday = friday + pandas.Timedelta(2, 'm')  #後面的參數對應 unit; w week / m minute 
print(saturday)
print('-----------------------')

#timestamp當作Index
dates = [pandas.Timestamp('2023, 1, 15'), pandas.Timestamp('2023, 8, 15'), pandas.Timestamp('2023-03-14')]
ts = pandas.Series(data = np.random.randn(3), index = dates)
print(ts)

2023-03-17 00:02:00
-----------------------
2023-01-15    0.302775
2023-08-15   -0.018098
2023-03-14   -0.248166
dtype: float64

In [4]:
#資料遺失偵測與填補
import pandas
import numpy as np
df = pandas.read_excel('1120314分析駕訓班學員違規資料.xlsx', sheet_name = '表三result')
#print(df)
#print(df.isnull())

is_no_rule_content = df.違規條款內容.isnull()
#print(is_no_rule_content)
df_no_rule_content = df[is_no_rule_content]
print(df_no_rule_content)
print('-----------------------')

#將null值填入
#df_no_rule_content['違規條款內容'] = df_no_rule_content['違規條款內容'].fillna(value = '未知')  #對特定的column直接賦予值
#print(df_no_rule_content)
#print('-----------------------')


df_no_rule_content['違規地點2'] = df_no_rule_content['違規地點2'].replace(to_replace = np.nan, value = '神秘的地點')
print(df_no_rule_content)

     駕駛人姓名       駕駛人證號       出生年月日 駕駛執照種類      取得駕照日期                 違規日期  \
2      仇雯嬿  A222191683  1973-08-20  普通大客車  2016-02-02  2022-12-28 09:11:00
3      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2022-01-26 16:16:00
4      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2022-10-19 15:09:00
5      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2022-12-22 09:36:00
6      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2023-02-20 09:45:00
...    ...         ...         ...    ...         ...                  ...
2722   黎德志  J122872036  1996-05-03  普通大貨車  2015-07-23  2022-03-16 11:02:00
2723   黎志康  H123483514  1986-12-26  職業聯結車  2020-07-22  2023-01-08 08:29:00
2724   黎志康  H123483514  1986-12-26  職業聯結車  2020-07-22  2022-04-19 08:45:00
2726   龍雲康  O100173771  1988-02-03  普通大客車  2019-03-25  2022-08-16 17:16:00
2727   龍雲康  O100173771  1988-02-03  普通大貨車  2015-11-13  2022-08-16 17:16:00

          違規條款 違規條款內容  違規所駕車輛號牌 違規所駕車輛車種     汽車所有人姓名   汽車所有人證號  汽車所有人生日  \
2     29309012    NaN  KLM-3110       汽車  萬興汽車貨運有限公司  53981679      0.0
3     29310012    NaN  KED-1776       汽車         NaN       NaN      NaN
4     29310012    NaN  KLF-7107       汽車    光洲交通有限公司  90572958      0.0
5     29310012    NaN  KLF-7107       汽車    光洲交通有限公司  90572958      0.0
6     29310012    NaN  KLF-7107       汽車    光洲交通有限公司  90572958      0.0
...        ...    ...       ...      ...         ...       ...      ...
2722  29319012    NaN  KEK-0502       汽車  明發環保工程有限公司  27300233      0.0
2723  29309012    NaN  KLH-0556       汽車  友義交通股份有限公司  43953359      0.0
2724  29314012    NaN  KLH-0556       汽車  友義交通股份有限公司  43953359      0.0
2726  29319012    NaN  KLA-9755       汽車    元賀交通有限公司  12766227      0.0
2727  29319012    NaN  KLA-9755       汽車    元賀交通有限公司  12766227      0.0

                  違規地點1 違規地點2
2            桃園區萬壽路與復興路   NaN
3     中壢區領航南路四段與青溪路二段口之   NaN
4               楊梅區金山街上   NaN
5          新北市林口區民族路82巷   NaN
6        蘆竹區機捷路二段靠近寶順街口   NaN
...                 ...   ...
2722  國道１號南向８３．５公里處　　　　   NaN
2723        平鎮區中豐路與新富街口   NaN
2724         平鎮區快速道路大溪端   NaN
2726   臺西鄉臺61線224公里處地磅站   NaN
2727   臺西鄉臺61線224公里處地磅站   NaN

[1545 rows x 15 columns]
-----------------------
     駕駛人姓名       駕駛人證號       出生年月日 駕駛執照種類      取得駕照日期                 違規日期  \
2      仇雯嬿  A222191683  1973-08-20  普通大客車  2016-02-02  2022-12-28 09:11:00
3      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2022-01-26 16:16:00
4      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2022-10-19 15:09:00
5      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2022-12-22 09:36:00
6      任茂林  H120028888  1975-09-27  普通大客車  2017-05-19  2023-02-20 09:45:00
...    ...         ...         ...    ...         ...                  ...
2722   黎德志  J122872036  1996-05-03  普通大貨車  2015-07-23  2022-03-16 11:02:00
2723   黎志康  H123483514  1986-12-26  職業聯結車  2020-07-22  2023-01-08 08:29:00
2724   黎志康  H123483514  1986-12-26  職業聯結車  2020-07-22  2022-04-19 08:45:00
2726   龍雲康  O100173771  1988-02-03  普通大客車  2019-03-25  2022-08-16 17:16:00
2727   龍雲康  O100173771  1988-02-03  普通大貨車  2015-11-13  2022-08-16 17:16:00

          違規條款 違規條款內容  違規所駕車輛號牌 違規所駕車輛車種     汽車所有人姓名   汽車所有人證號  汽車所有人生日  \
2     29309012    NaN  KLM-3110       汽車  萬興汽車貨運有限公司  53981679      0.0
3     29310012    NaN  KED-1776       汽車         NaN       NaN      NaN
4     29310012    NaN  KLF-7107       汽車    光洲交通有限公司  90572958      0.0
5     29310012    NaN  KLF-7107       汽車    光洲交通有限公司  90572958      0.0
6     29310012    NaN  KLF-7107       汽車    光洲交通有限公司  90572958      0.0
...        ...    ...       ...      ...         ...       ...      ...
2722  29319012    NaN  KEK-0502       汽車  明發環保工程有限公司  27300233      0.0
2723  29309012    NaN  KLH-0556       汽車  友義交通股份有限公司  43953359      0.0
2724  29314012    NaN  KLH-0556       汽車  友義交通股份有限公司  43953359      0.0
2726  29319012    NaN  KLA-9755       汽車    元賀交通有限公司  12766227      0.0
2727  29319012    NaN  KLA-9755       汽車    元賀交通有限公司  12766227      0.0

                  違規地點1  違規地點2
2            桃園區萬壽路與復興路  神秘的地點
3     中壢區領航南路四段與青溪路二段口之  神秘的地點
4               楊梅區金山街上  神秘的地點
5          新北市林口區民族路82巷  神秘的地點
6        蘆竹區機捷路二段靠近寶順街口  神秘的地點
...                 ...    ...
2722  國道１號南向８３．５公里處　　　　  神秘的地點
2723        平鎮區中豐路與新富街口  神秘的地點
2724         平鎮區快速道路大溪端  神秘的地點
2726   臺西鄉臺61線224公里處地磅站  神秘的地點
2727   臺西鄉臺61線224公里處地磅站  神秘的地點

[1545 rows x 15 columns]

C:\Users\mi83\AppData\Local\Temp\ipykernel_6384\3122135454.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_rule_content['違規地點2'] = df_no_rule_content['違規地點2'].replace(to_replace = np.nan, value = '神秘的地點')

In [1]:
#排除離群值 -> 自行定義function
import numpy as np
import pandas as pd

outliers = []  #紀錄離群值的list


#找出與平均值之差超過3個標準差的值
def detect_outlier(data):
    #data是pandas的dataframe
    threshold = 3
    mean = np.mean(data)
    std = np.std(data)
    
    for y in data:
        z_score = (y - mean) / std  #標準分數
        if np.abs(z_score) > threshold:
            outliers.append(y)
    
    return outliers


#my_data = [60,65,70,55,59,78,80,92,95,80,77,100,1000,10,47]
#my_outliers = detect_outlier(my_data)
#print(my_outliers)


push_pay_list = pd.read_excel('1120309燃料費催繳清冊1061231以前__增加排除條件.xlsx', sheet_name = '106年以前燃料費催繳清冊__增加排除狀態')
print(push_pay_list)
#print(outliers)
print('---------------------------------')
outlier_push_pay = detect_outlier(push_pay_list['應納金額'])
#print(outlier_push_pay)
#print(outliers)
print('---------------------------------')




#濾出超過3個標準差的資料(以「應納金額」欄位值做運算)
def cal_zscore(data):
    #data是某個要判斷的list
    zscore = []
    mean = np.mean(data)
    std = np.std(data)
    
    print(mean)
    print(std)
    return (data - mean) / std

#print(cal_zscore(push_pay_list['應納金額']))
print('---------------------------------')

print(type(push_pay_list['應納金額']))
print(push_pay_list['應納金額'])
z_scores = cal_zscore(push_pay_list['應納金額'])
abs_z_scores = np.abs(z_scores)
test = (abs_z_scores > 3)  #會是一個True與False組成的series
print(type(test))
test1 = [True] * 37352
print(test)

print('---------------------------------')

filtered_push_pay_list = push_pay_list[abs_z_scores > 3]  #看起來dataframe中的filter([]中)只在乎True或False, 只要是True的就會留下
print(filtered_push_pay_list)
print(push_pay_list[test1])

       起始年度  所站        車主證號  車主名稱       車號   年度 期別  計費起日  計費迄日      計費異動代碼  \
0        88  50  ***J003717  許月詹珍  KQ-4893   89  9   101  1231   9000　二代轉入
1       105  50  ***J024698   魯茱麗  JPQ-023  105  B   101  1231   9999　批次設欠
2       106  50  ***J024698   魯茱麗  JPQ-023  106  B   101  1231   9999　批次設欠
3       101  50  ***J040564  劉桑雅樂  BMY-160  101  B   213  1231  9005　偶數年欠費
4       102  50  ***J040564  劉桑雅樂  BMY-160  101  B   101   212  9005　偶數年欠費
...     ...  ..         ...   ...      ...  ... ..   ...   ...         ...
37347   103  54  Y220117884   翁陵紋  BJ2-622  103  B   901  1231   9000　二代轉入
37348   102  54  Y220486580   何美華  NW6-968  102  B   506  1231   9000　二代轉入
37349   103  54  Y220538061   沈瓊櫻  IIG-703  103  B   805  1231   9000　二代轉入
37350    91  54  Z200112394   王淑玉  GZ-1942   91  4   101  1231   9000　二代轉入
37351    91  54  Z200112394   王淑玉  KY-7323   91  4   101  1231   9000　二代轉入

       ...        催繳單號                 限繳日期                 達退日期    達退狀態  \
0      ...   899101956  2007-12-31 00:00:00  2007-10-24 00:00:00  F 寄存送達
1      ...  A5C2000001  2017-09-30 00:00:00  2017-09-12 16:52:19  D 公示送達
2      ...  A6C2000002  2017-12-31 00:00:00  2017-11-22 00:00:00  F 寄存送達
3      ...  A1C5000002  2014-05-31 00:00:00  2014-04-21 12:58:51  F 寄存送達
4      ...  A1C5000002  2014-05-31 00:00:00  2014-04-21 12:58:51  F 寄存送達
...    ...         ...                  ...                  ...     ...
37347  ...  A3C0000046  2015-03-02 00:00:00  2014-11-25 18:42:21  F 寄存送達
37348  ...  A2C5154802  2014-05-31 00:00:00  2014-04-21 00:00:00  F 寄存送達
37349  ...  A3C2000027  2015-12-31 00:00:00  2015-12-10 09:29:06    1 送達
37350  ...   914070766  2006-12-31 00:00:00  2006-10-17 00:00:00  F 寄存送達
37351  ...   914070767  2006-12-31 00:00:00  2006-10-17 00:00:00  F 寄存送達

        本費狀態 強執狀態_移送狀態               最後異動時間  \
0      2 假處分         無  2015-06-10 22:37:00
1       0 催繳        排除  2019-04-11 08:33:00
2       0 催繳        排除  2019-04-11 08:33:00
3      2 假處分        排除  2019-04-11 08:34:00
4      2 假處分        排除  2019-04-11 08:34:00
...      ...       ...                  ...
37347   0 催繳         無  2019-11-22 11:17:00
37348  2 假處分         無  2019-05-06 14:42:00
37349   0 催繳         無                  NaN
37350  2 假處分         無  2014-08-28 22:53:00
37351  2 假處分         無  2014-08-28 22:53:00

                                                  其他催繳單號 車主是否死亡       死亡日期
0                                                    NaN      N        NaN
1                                                    NaN      N        NaN
2                                                    NaN      N        NaN
3      1000213;1020212;000900;000000;000847;000053;00...      N        NaN
4      1000213;1020212;000900;000000;000847;000053;00...      N        NaN
...                                                  ...    ...        ...
37347  1030901;1031231;000150;000000;000000;000000;00...      N        NaN
37348  1020506;1021231;000294;000000;000000;000000;00...      N        NaN
37349                                1030805;1031231;182      Y  1091122.0
37350                                                NaN      N        NaN
37351                                                NaN      N        NaN

[37352 rows x 23 columns]
---------------------------------
---------------------------------
---------------------------------
<class 'pandas.core.series.Series'>
0        2000
1         450
2         450
3         847
4          53
         ...
37347     150
37348     294
37349     182
37350    1116
37351    4800
Name: 應納金額, Length: 37352, dtype: int64
1977.9895320197045
2528.9874021481282
<class 'pandas.core.series.Series'>
0        False
1        False
2        False
3        False
4        False
         ...
37347    False
37348    False
37349    False
37350    False
37351    False
Name: 應納金額, Length: 37352, dtype: bool
---------------------------------
       起始年度  所站      車主證號             車主名稱       車號   年度 期別  計費起日  計費迄日  \
42       87  50  02747948              吉盛號   RN-773   89  9   101  1231
43       88  50  02747948              吉盛號   RN-773   89  9   101  1231
91      102  50  14821252  新竹縣達那原住民清潔勞動合作社  9051-TV  102  4   101  1231
97       85  50  22231814         新剛工程有限公司  JP-2422   89  9   101  1231
98       86  50  22231814         新剛工程有限公司  JP-2422   89  9   101  1231
...     ...  ..       ...              ...      ...  ... ..   ...   ...
32878    88  54  49807994              和成行  MB-6997   89  9   101  1231
32949    89  54  66836699          昇輝土木包工業   RW-163   89  9   101  1231
32974    88  54  83347035            龍福企業社   9F-128   89  9   101  1231
32975    89  54  83347035            龍福企業社   9F-128   89  9   101  1231
33055    89  54  97003897       松泉環保工程有限公司   Q7-163   89  9   101  1231

              計費異動代碼  ...       催繳單號                 限繳日期  \
42     9006　無牌違規（二代)  ...  899122181  2011-12-31 00:00:00
43     9006　無牌違規（二代)  ...  899122181  2011-12-31 00:00:00
91         9000　二代轉入  ...  A24112640  2013-12-31 00:00:00
97         9000　二代轉入  ...  899122500  2011-12-31 00:00:00
98         9000　二代轉入  ...  899122500  2011-12-31 00:00:00
...              ...  ...        ...                  ...
32878  9006　無牌違規（二代)  ...  899135061  2011-12-31 00:00:00
32949  9006　無牌違規（二代)  ...  899135403  2011-12-31 00:00:00
32974  9006　無牌違規（二代)  ...  899136596  2011-12-31 00:00:00
32975  9006　無牌違規（二代)  ...  899136596  2011-12-31 00:00:00
33055  9006　無牌違規（二代)  ...  899136020  2011-12-31 00:00:00

                      達退日期    達退狀態   本費狀態 強執狀態_移送狀態               最後異動時間  \
42     2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-08-04 11:03:00
43     2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-08-04 11:03:00
91     2013-10-25 00:00:00  F 寄存送達  2 假處分         無  2015-09-23 15:59:00
97     2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-08-04 11:03:00
98     2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-08-04 11:03:00
...                    ...     ...    ...       ...                  ...
32878  2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-12-17 10:03:00
32949  2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-12-17 10:03:00
32974  2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-11-04 14:41:00
32975  2011-11-16 00:00:00  F 寄存送達  2 假處分         無  2015-11-04 14:41:00
33055  2011-11-14 00:00:00    1 送達  2 假處分         無  2015-12-17 10:03:00

      其他催繳單號 車主是否死亡 死亡日期
42       NaN      N  NaN
43       NaN      N  NaN
91       NaN      N  NaN
97       NaN      N  NaN
98       NaN      N  NaN
...      ...    ...  ...
32878    NaN      N  NaN
32949    NaN      N  NaN
32974    NaN      N  NaN
32975    NaN      N  NaN
33055    NaN      N  NaN

[189 rows x 23 columns]
       起始年度  所站        車主證號  車主名稱       車號   年度 期別  計費起日  計費迄日      計費異動代碼  \
0        88  50  ***J003717  許月詹珍  KQ-4893   89  9   101  1231   9000　二代轉入
1       105  50  ***J024698   魯茱麗  JPQ-023  105  B   101  1231   9999　批次設欠
2       106  50  ***J024698   魯茱麗  JPQ-023  106  B   101  1231   9999　批次設欠
3       101  50  ***J040564  劉桑雅樂  BMY-160  101  B   213  1231  9005　偶數年欠費
4       102  50  ***J040564  劉桑雅樂  BMY-160  101  B   101   212  9005　偶數年欠費
...     ...  ..         ...   ...      ...  ... ..   ...   ...         ...
37347   103  54  Y220117884   翁陵紋  BJ2-622  103  B   901  1231   9000　二代轉入
37348   102  54  Y220486580   何美華  NW6-968  102  B   506  1231   9000　二代轉入
37349   103  54  Y220538061   沈瓊櫻  IIG-703  103  B   805  1231   9000　二代轉入
37350    91  54  Z200112394   王淑玉  GZ-1942   91  4   101  1231   9000　二代轉入
37351    91  54  Z200112394   王淑玉  KY-7323   91  4   101  1231   9000　二代轉入

       ...        催繳單號                 限繳日期                 達退日期    達退狀態  \
0      ...   899101956  2007-12-31 00:00:00  2007-10-24 00:00:00  F 寄存送達
1      ...  A5C2000001  2017-09-30 00:00:00  2017-09-12 16:52:19  D 公示送達
2      ...  A6C2000002  2017-12-31 00:00:00  2017-11-22 00:00:00  F 寄存送達
3      ...  A1C5000002  2014-05-31 00:00:00  2014-04-21 12:58:51  F 寄存送達
4      ...  A1C5000002  2014-05-31 00:00:00  2014-04-21 12:58:51  F 寄存送達
...    ...         ...                  ...                  ...     ...
37347  ...  A3C0000046  2015-03-02 00:00:00  2014-11-25 18:42:21  F 寄存送達
37348  ...  A2C5154802  2014-05-31 00:00:00  2014-04-21 00:00:00  F 寄存送達
37349  ...  A3C2000027  2015-12-31 00:00:00  2015-12-10 09:29:06    1 送達
37350  ...   914070766  2006-12-31 00:00:00  2006-10-17 00:00:00  F 寄存送達
37351  ...   914070767  2006-12-31 00:00:00  2006-10-17 00:00:00  F 寄存送達

        本費狀態 強執狀態_移送狀態               最後異動時間  \
0      2 假處分         無  2015-06-10 22:37:00
1       0 催繳        排除  2019-04-11 08:33:00
2       0 催繳        排除  2019-04-11 08:33:00
3      2 假處分        排除  2019-04-11 08:34:00
4      2 假處分        排除  2019-04-11 08:34:00
...      ...       ...                  ...
37347   0 催繳         無  2019-11-22 11:17:00
37348  2 假處分         無  2019-05-06 14:42:00
37349   0 催繳         無                  NaN
37350  2 假處分         無  2014-08-28 22:53:00
37351  2 假處分         無  2014-08-28 22:53:00

                                                  其他催繳單號 車主是否死亡       死亡日期
0                                                    NaN      N        NaN
1                                                    NaN      N        NaN
2                                                    NaN      N        NaN
3      1000213;1020212;000900;000000;000847;000053;00...      N        NaN
4      1000213;1020212;000900;000000;000847;000053;00...      N        NaN
...                                                  ...    ...        ...
37347  1030901;1031231;000150;000000;000000;000000;00...      N        NaN
37348  1020506;1021231;000294;000000;000000;000000;00...      N        NaN
37349                                1030805;1031231;182      Y  1091122.0
37350                                                NaN      N        NaN
37351                                                NaN      N        NaN

[37352 rows x 23 columns]

In [83]:
#資料的合併
import pandas as pd

#dataframe1 and 2
dataframe1 = pd.DataFrame({'lkey':['foo','bar','baz','foo'], 'lseq':['0001','0002','0003','0004'], 'value':[1,2,3,4]})
dataframe2 = pd.DataFrame({'rkey':['foo','bar','qux','bar','tes'], 'rseq':['0050','0002','0313','4105','5510'], 'value':[1,6,7,5,10]})
print(dataframe1)
print('----------------------')
print(dataframe2)
print('----------------------')

#merge -> left join
dataframe1.merge(dataframe2, left_on = ['lkey','lseq'], right_on = ['rkey','rseq'], how = 'left')  #on的順序要一樣!!


#join -> 特別的操作，不同於database中table的join @@
#屬於index-based
#相同index對接(同一個row的資料相連), column - index對接 -> 很奇怪
#橫向發展
print(dataframe1.join(dataframe2, lsuffix = '_left', rsuffix = '_right', how = 'right') )


#concat -> 跟join一樣，index-based, (不知所以然)
#可橫可縱向發展 -> 縱向發展就如同union all(前提: column name一致)
#單純地把資料接起來，不像merge能夠根據一樣的內容來連接
frames = [dataframe1, dataframe2]
pd.concat(frames, keys=['a','b'], axis = 0, join = 'inner')  #keys: 階層式的索引; axis: 0 index / 1 column; join: 要變瘦or變胖: inner 變瘦 / outer 變胖


print('----------------------')
#stack的用法 -> 把column轉成row
df_stack = dataframe1.stack()
print(df_stack)
print('----------------------')

#row轉成column
df_unstack = df_stack.unstack()  
print(df_unstack)

  lkey  lseq  value
0  foo  0001      1
1  bar  0002      2
2  baz  0003      3
3  foo  0004      4
----------------------
  rkey  rseq  value
0  foo  0050      1
1  bar  0002      6
2  qux  0313      7
3  bar  4105      5
4  tes  5510     10
----------------------
  lkey  lseq  value_left rkey  rseq  value_right
0  foo  0001         1.0  foo  0050            1
1  bar  0002         2.0  bar  0002            6
2  baz  0003         3.0  qux  0313            7
3  foo  0004         4.0  bar  4105            5
4  NaN   NaN         NaN  tes  5510           10
----------------------
0  lkey      foo
   lseq     0001
   value       1
1  lkey      bar
   lseq     0002
   value       2
2  lkey      baz
   lseq     0003
   value       3
3  lkey      foo
   lseq     0004
   value       4
dtype: object
----------------------
  lkey  lseq value
0  foo  0001     1
1  bar  0002     2
2  baz  0003     3
3  foo  0004     4

In [16]:
# Initializing list
test_list = [1, 6, 3, 5, 3, 4]

result = {item*2 for item in test_list}
print(type(result))

<class 'set'>